version: "3.9"

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: always

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always